stages:
  - test

jobs:
  include:
    - name: Tests Webpack 4
      stage: test
      language: node_js
      node_js:
        - "12"
        - "11"
      before_install:
        - yarn global add webpack@^4.0.0
        - export NODE_PATH=$(yarn global dir)/node_modules
      script: yarn run travis
