version: 2.1

jobs:
  test:
    parameters:
      node-version:
        type: string
    docker:
      - image: cimg/node:<< parameters.node-version >>
    steps:
      - checkout
      - run: |
          echo "Node version: $(node --version)"
          echo "NPM version:  $(npm --version)"
          npm install
          npm test

workflows:
  all-tests:
    jobs:
      - test:
          matrix:
            parameters:
              node-version:
                # See https://nodejs.org/en/about/releases/
                - "current"  # Right now: 16.3
                - "lts"      # Right now: 14.17
                - "12.22.1"  # Oldest maintenance LTS, End-of-Life 2022-04-30
          name: test-on-node-<< matrix.node-version >>
